#配置数据源和项目名称
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password
  kafka:
    bootstrap-servers: 192.168.1.10:9092,192.168.1.11:9092,192.168.1.12:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer



server:
  port: 8001


#配置mybatis的mapper和domain的位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.fhp.usercenter.domain

#配置eureka的注册中心
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
  #instance:
   # instance-id: ${spring.application.name}:${server.port}  #//这一行必须加，不然会注册失败
