#配置数据源和项目名称
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password


server:
  port: 8001

#配置mybatis的mapper和domain的位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.fhp.usercenter.domain

#配置eureka的注册中心
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/